"""Deterministic off-policy coverage inputs, never authentic reach or policies.

Inspired by DeepStack's recursive strength-split ranges, but with an explicit
20% uniform floor. Every resulting payoff must be generated by a native solve;
this module generates requests only and never invents values or strategies.
"""
from __future__ import annotations

import copy
import numpy as np

from cash_checkdown import exact_cash_checkdown_features
from cash_value_dataset import validate_label
from native_value_dataset import board_family, identity_hash, legal_combos


def _strength_split(equity, legal, rng):
    keys = np.flatnonzero(legal)
    ordered = keys[np.lexsort((keys,equity[keys]))]
    result = np.zeros(1326,dtype=np.float64)
    pending = [(0,len(ordered),1.)]
    while pending:
        start,stop,mass = pending.pop()
        if stop-start == 1:
            result[ordered[start]] = mass
            continue
        middle = (start+stop)//2
        lower = mass*float(rng.random())
        pending.append((middle,stop,mass-lower))
        pending.append((start,middle,lower))
    # Declared range-generation choice, not a poker-policy fallback. It avoids
    # underflow and keeps both players' legal hands positively represented.
    result = .8*result+.2*legal/legal.sum()
    return result/result.sum()


def synthetic_cash_turn_requests(reference_label: dict, investment_units: list[int],
                                 count: int, seed: int, excluded_families=()):
    """Return a pinned request corpus for at most 64 distinct new flop families.

    The caller supplies validated native reference semantics and empirical
    training commitment amounts in cents, including duplicates/frequencies.
    Cards are sampled independently of labels. Ranges use exact forced-runout
    equity against uniform legal hands, not teacher values or a future deck.
    Exclude all training/development/holdout families before solving anything.
    """
    if type(count) is not int or not 1 <= count <= 64:
        raise ValueError("synthetic cash request count must be an integer in 1..64")
    if type(seed) is not int or not 0 <= seed < 2**32:
        raise ValueError("synthetic cash seed must be an integer in 0..2^32-1")
    if (type(investment_units) is not list or not investment_units
            or any(type(value) is not int or not 25 <= value < 500 for value in investment_units)):
        raise ValueError("synthetic cash commitments must be empirical integer cents in 25..499")
    validate_label(reference_label)
    template = reference_label["input"]
    rules = template["game"]["cash_rules"]
    if rules["unitsPerBb"] != 25:
        raise ValueError("synthetic cash coverage currently requires NL25 cent units")
    excluded = set()
    for family in excluded_families:
        if (type(family) is not tuple or len(family) != 3
                or any(type(card) is not int or not 0 <= card < 52 for card in family)
                or len(set(family)) != 3 or board_family(family) != family):
            raise ValueError("synthetic cash exclusions must be canonical flop-family tuples")
        excluded.add(family)
    rng = np.random.default_rng(seed)
    cases = []
    # Bound rejection sampling even if the caller excludes most board space.
    for _ in range(10000):
        if len(cases) == count:
            break
        board = list(map(int,rng.choice(52,size=4,replace=False)))
        board[:3] = sorted(board[:3])
        family = board_family(board)
        if family in excluded:
            continue
        legal = legal_combos(board)
        uniform = np.tile(legal/legal.sum(),(2,1))
        amount = int(rng.choice(investment_units))
        investment = amount/rules["unitsPerBb"]
        _,equity = exact_cash_checkdown_features(board,uniform,[investment]*2,rules)
        if (equity.shape != (2,1326) or not np.isfinite(equity).all()
                or np.any((equity < 0) | (equity > 1))):
            raise ValueError("synthetic cash strength must be finite exact equity in [0,1]")
        ranges = np.stack([_strength_split(equity[seat],legal,rng) for seat in (0,1)])
        config = copy.deepcopy(template)
        config.update(iterations=64,averaging_delay=0,river_refinement_iterations=0,regret_matching_plus=False)
        config["state"].update(board=board,ranges=ranges.tolist(),invested_bb=[investment]*2)
        cases.append(dict(index=len(cases),flop_family=list(family),investment_units=amount,
                          input_sha256=identity_hash(config),solve_input=config))
        excluded.add(family)
    if len(cases) != count:
        raise ValueError("synthetic cash exclusions exhausted bounded board sampling")
    return dict(schema="hu-cash-synthetic-turn-requests-v1",status="research_only",active=False,
                kind="off-policy-strength-split-ranges-not-authentic-reach",seed=seed,
                source_template_input_sha256=identity_hash(template),uniform_floor=.2,
                strength="exact-forced-runout-equity-against-uniform-legal-hands",
                investment_sampling="empirical-training-context-counts-not-authentic-hand-reach",
                own_values_generated=False,policies_generated=False,cases=cases)
